import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  writeFileSync,
  rmSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  detectCopilotSignals,
  formatCopilotTrailer,
  writeCopilotMarker,
  clearCopilotMarker,
  findGitRoot,
} from "../core/copilot-detect.js";
import type { CopilotSignal } from "../core/copilot-detect.js";

// ------------------------------------------------------------------ //
// Helpers
// ------------------------------------------------------------------ //

function makeTempRepo(): string {
  const dir = join(tmpdir(), `ai-footprint-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(join(dir, ".git"), { recursive: true });
  return dir;
}

function cleanupDir(dir: string): void {
  try {
    rmSync(dir, { recursive: true, force: true });
  } catch { /* best-effort */ }
}

// ------------------------------------------------------------------ //
// Tests: detectCopilotSignals
// ------------------------------------------------------------------ //

describe("detectCopilotSignals", () => {
  let tempRepo: string;

  beforeEach(() => {
    tempRepo = makeTempRepo();
  });

  afterEach(() => {
    cleanupDir(tempRepo);
    // Clean env vars — all agents
    delete process.env.GH_COPILOT;
    delete process.env.GITHUB_COPILOT_CLI;
    delete process.env.GH_PROMPT;
    delete process.env.CLAUDE_CODE;
    delete process.env.CLAUDE_CODE_ENTRY;
    delete process.env.ANTHROPIC_API_KEY;
    delete process.env.CURSOR_TRACE_ID;
    delete process.env.CURSOR_CHANNEL;
    delete process.env.TERM_PROGRAM;
    delete process.env.LOVABLE_TOKEN;
    delete process.env.GPTENGINEER_TOKEN;
  });

  it("returns empty array when no signals present", () => {
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.deepEqual(signals, []);
  });

  it("detects GH_COPILOT environment variable", () => {
    process.env.GH_COPILOT = "1";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "copilot-cli");
    assert.equal(signals[0].confidence, "high");
    assert.ok(signals[0].evidence.some((e) => e.includes("GH_COPILOT")));
  });

  it("detects GITHUB_COPILOT_CLI environment variable", () => {
    process.env.GITHUB_COPILOT_CLI = "1";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "copilot-cli");
  });

  it("detects GH_PROMPT with copilot mention", () => {
    process.env.GH_PROMPT = "copilot suggest";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "copilot-cli");
    assert.ok(signals[0].evidence.some((e) => e.includes("GH_PROMPT")));
  });

  it("ignores GH_PROMPT without copilot mention", () => {
    process.env.GH_PROMPT = "something else";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 0);
  });

  it("detects 'Co-authored-by: copilot' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Fix bug\n\nCo-authored-by: Copilot <copilot@github.com>",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "copilot-chat");
    assert.equal(signals[0].confidence, "medium");
  });

  it("detects 'Co-authored-by: [bot]' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Add feature\n\nCo-authored-by: github-actions[bot]",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "copilot-chat");
  });

  it("detects 'github copilot' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "This was generated by GitHub Copilot",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "copilot-chat");
  });

  it("detects 'copilot agent' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "refactor: copilot-agent applied cleanup",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "copilot-chat");
  });

  it("detects 'Generated by Copilot' prefix", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Generated by Copilot\n\nAdded helper function",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "copilot-chat");
  });

  it("does not match unrelated commit messages", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Fix authentication bug in login flow",
    });
    assert.equal(signals.length, 0);
  });

  it("detects marker file written by extension", () => {
    writeCopilotMarker(["src/app.ts", "src/utils.ts"], tempRepo);
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "copilot-agent");
    assert.equal(signals[0].confidence, "high");
    assert.deepEqual(signals[0].files, ["src/app.ts", "src/utils.ts"]);
  });

  it("combines multiple signals", () => {
    process.env.GH_COPILOT = "1";
    writeCopilotMarker(["index.ts"], tempRepo);
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Co-authored-by: Copilot <copilot@github.com>",
    });
    assert.equal(signals.length, 3); // marker + CLI + commit msg
  });

  // ---- Claude Code ----

  it("detects CLAUDE_CODE environment variable", () => {
    process.env.CLAUDE_CODE = "1";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "claude-code");
    assert.equal(signals[0].confidence, "high");
    assert.ok(signals[0].evidence.some((e) => e.includes("CLAUDE_CODE")));
  });

  it("detects CLAUDE_CODE_ENTRY environment variable", () => {
    process.env.CLAUDE_CODE_ENTRY = "/usr/local/bin/claude";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "claude-code");
  });

  it("detects ANTHROPIC_API_KEY environment variable", () => {
    process.env.ANTHROPIC_API_KEY = "sk-ant-xxx";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "claude-code");
  });

  it("detects 'Co-authored-by: Claude' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Fix tests\n\nCo-authored-by: Claude <claude@anthropic.com>",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "claude-code");
    assert.equal(signals[0].confidence, "medium");
  });

  it("detects 'claude code' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "refactor: claude-code applied cleanup",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "claude-code");
  });

  it("detects 'Generated by Claude' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Generated by Claude\n\nAdded error handling",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "claude-code");
  });

  it("detects 'Anthropic Claude' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Built with Anthropic Claude assistance",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "claude-code");
  });

  // ---- Cursor ----

  it("detects CURSOR_TRACE_ID environment variable", () => {
    process.env.CURSOR_TRACE_ID = "abc123";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "cursor");
    assert.equal(signals[0].confidence, "high");
  });

  it("detects TERM_PROGRAM=cursor", () => {
    process.env.TERM_PROGRAM = "cursor";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "cursor");
  });

  it("detects CURSOR_CHANNEL environment variable", () => {
    process.env.CURSOR_CHANNEL = "stable";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "cursor");
  });

  it("detects 'cursor composer' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "feat: cursor composer added new routes",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "cursor");
    assert.equal(signals[0].confidence, "medium");
  });

  it("detects 'Generated by Cursor' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Generated by Cursor\n\nRefactored auth module",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "cursor");
  });

  it("ignores TERM_PROGRAM without cursor value", () => {
    process.env.TERM_PROGRAM = "vscode";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 0);
  });

  // ---- Lovable ----

  it("detects LOVABLE_TOKEN environment variable", () => {
    process.env.LOVABLE_TOKEN = "tok_xxx";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "lovable");
    assert.equal(signals[0].confidence, "high");
  });

  it("detects GPTENGINEER_TOKEN environment variable", () => {
    process.env.GPTENGINEER_TOKEN = "tok_xxx";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "lovable");
  });

  it("detects 'lovable-dev' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Add landing page\n\nCo-authored-by: lovable-dev <bot@lovable.dev>",
    });
    const lovableSignals = signals.filter((s) => s.source === "lovable");
    assert.ok(lovableSignals.length >= 1);
  });

  it("detects 'gpt engineer' in commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Built with GPT Engineer",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "lovable");
  });

  it("detects lovable-dev[bot] author via commit message", () => {
    const signals = detectCopilotSignals({
      repoRoot: tempRepo,
      commitMessage: "Initial commit",
      commitAuthor: "lovable-dev[bot]",
    });
    assert.equal(signals.length, 1);
    assert.equal(signals[0].source, "lovable");
  });

  // ---- Cross-agent ----

  it("detects multiple different agents simultaneously", () => {
    process.env.CLAUDE_CODE = "1";
    process.env.CURSOR_TRACE_ID = "xyz";
    const signals = detectCopilotSignals({ repoRoot: tempRepo });
    assert.equal(signals.length, 2);
    const sources = signals.map((s) => s.source);
    assert.ok(sources.includes("claude-code"));
    assert.ok(sources.includes("cursor"));
  });
});

// ------------------------------------------------------------------ //
// Tests: formatCopilotTrailer
// ------------------------------------------------------------------ //

describe("formatCopilotTrailer", () => {
  it("returns empty string for no signals", () => {
    assert.equal(formatCopilotTrailer([]), "");
  });

  it("formats single CLI signal", () => {
    const signals: CopilotSignal[] = [
      { source: "copilot-cli", confidence: "high", evidence: ["GH_COPILOT"] },
    ];
    const trailer = formatCopilotTrailer(signals);
    assert.equal(trailer, "copilot (copilot-cli); confidence: high");
  });

  it("formats single agent signal", () => {
    const signals: CopilotSignal[] = [
      {
        source: "copilot-agent",
        confidence: "high",
        evidence: ["marker file"],
        files: ["a.ts"],
      },
    ];
    const trailer = formatCopilotTrailer(signals);
    assert.equal(trailer, "copilot (copilot-agent); confidence: high");
  });

  it("formats multiple sources with highest confidence", () => {
    const signals: CopilotSignal[] = [
      { source: "copilot-agent", confidence: "high", evidence: ["marker"] },
      { source: "copilot-chat", confidence: "medium", evidence: ["msg pattern"] },
    ];
    const trailer = formatCopilotTrailer(signals);
    assert.equal(
      trailer,
      "copilot (copilot-agent, copilot-chat); confidence: high",
    );
  });

  it("deduplicates sources", () => {
    const signals: CopilotSignal[] = [
      { source: "copilot-cli", confidence: "high", evidence: ["a"] },
      { source: "copilot-cli", confidence: "high", evidence: ["b"] },
    ];
    const trailer = formatCopilotTrailer(signals);
    assert.equal(trailer, "copilot (copilot-cli); confidence: high");
  });

  it("formats Claude Code signal", () => {
    const signals: CopilotSignal[] = [
      { source: "claude-code", confidence: "high", evidence: ["CLAUDE_CODE"] },
    ];
    const trailer = formatCopilotTrailer(signals);
    assert.equal(trailer, "claude (claude-code); confidence: high");
  });

  it("formats Cursor signal", () => {
    const signals: CopilotSignal[] = [
      { source: "cursor", confidence: "high", evidence: ["CURSOR_TRACE_ID"] },
    ];
    const trailer = formatCopilotTrailer(signals);
    assert.equal(trailer, "cursor (cursor); confidence: high");
  });

  it("formats Lovable signal", () => {
    const signals: CopilotSignal[] = [
      { source: "lovable", confidence: "high", evidence: ["LOVABLE_TOKEN"] },
    ];
    const trailer = formatCopilotTrailer(signals);
    assert.equal(trailer, "lovable (lovable); confidence: high");
  });

  it("formats mixed agents from different families", () => {
    const signals: CopilotSignal[] = [
      { source: "copilot-cli", confidence: "high", evidence: ["env"] },
      { source: "claude-code", confidence: "medium", evidence: ["msg"] },
    ];
    const trailer = formatCopilotTrailer(signals);
    assert.equal(trailer, "copilot-cli, claude-code; confidence: high");
  });
});

// ------------------------------------------------------------------ //
// Tests: writeCopilotMarker / clearCopilotMarker
// ------------------------------------------------------------------ //

describe("copilot marker file management", () => {
  let tempRepo: string;

  beforeEach(() => {
    tempRepo = makeTempRepo();
  });

  afterEach(() => {
    cleanupDir(tempRepo);
  });

  it("creates marker directory and file", () => {
    writeCopilotMarker(["src/index.ts"], tempRepo);
    const markerPath = join(tempRepo, ".ai-footprint", "copilot-pending.json");
    assert.ok(existsSync(markerPath));

    const data = JSON.parse(
      require("node:fs").readFileSync(markerPath, "utf-8"),
    );
    assert.deepEqual(data.files, ["src/index.ts"]);
    assert.ok(data.updatedAt);
  });

  it("merges files across multiple writes", () => {
    writeCopilotMarker(["a.ts"], tempRepo);
    writeCopilotMarker(["b.ts"], tempRepo);

    const markerPath = join(tempRepo, ".ai-footprint", "copilot-pending.json");
    const data = JSON.parse(
      require("node:fs").readFileSync(markerPath, "utf-8"),
    );
    assert.deepEqual(data.files, ["a.ts", "b.ts"]);
  });

  it("deduplicates files", () => {
    writeCopilotMarker(["a.ts", "b.ts"], tempRepo);
    writeCopilotMarker(["a.ts", "c.ts"], tempRepo);

    const markerPath = join(tempRepo, ".ai-footprint", "copilot-pending.json");
    const data = JSON.parse(
      require("node:fs").readFileSync(markerPath, "utf-8"),
    );
    assert.deepEqual(data.files, ["a.ts", "b.ts", "c.ts"]);
  });

  it("clearCopilotMarker removes the file", () => {
    writeCopilotMarker(["a.ts"], tempRepo);
    const markerPath = join(tempRepo, ".ai-footprint", "copilot-pending.json");
    assert.ok(existsSync(markerPath));

    clearCopilotMarker(tempRepo);
    assert.ok(!existsSync(markerPath));
  });

  it("clearCopilotMarker is safe when file does not exist", () => {
    // Should not throw
    clearCopilotMarker(tempRepo);
  });
});

// ------------------------------------------------------------------ //
// Tests: findGitRoot
// ------------------------------------------------------------------ //

describe("findGitRoot", () => {
  let tempRepo: string;

  beforeEach(() => {
    tempRepo = makeTempRepo();
    // Create a nested directory
    mkdirSync(join(tempRepo, "src", "deep"), { recursive: true });
  });

  afterEach(() => {
    cleanupDir(tempRepo);
  });

  it("finds root from the repo root itself", () => {
    const root = findGitRoot(tempRepo);
    assert.equal(root, tempRepo);
  });

  it("finds root from a nested directory", () => {
    const root = findGitRoot(join(tempRepo, "src", "deep"));
    assert.equal(root, tempRepo);
  });

  it("returns null when no .git directory exists", () => {
    const noGitDir = join(tmpdir(), `no-git-${Date.now()}`);
    mkdirSync(noGitDir, { recursive: true });
    try {
      const root = findGitRoot(noGitDir);
      // May find an ancestor .git — that's OK; just check it doesn't crash
      assert.ok(root === null || typeof root === "string");
    } finally {
      cleanupDir(noGitDir);
    }
  });
});

// ------------------------------------------------------------------ //
// Tests: Hook integration — trailer generation with Copilot signals
// ------------------------------------------------------------------ //

describe("hook integration — Copilot trailer in commit-msg", () => {
  it("generates combined trailer with matches and Copilot signal", () => {
    // Simulate what the updated commitMsg() does:
    const matchCount = 2;
    const models = new Set(["gpt-4.1"]);
    const copilotSignals: CopilotSignal[] = [
      { source: "copilot-agent", confidence: "high", evidence: ["marker"] },
    ];

    const trailerParts: string[] = [];

    if (matchCount > 0) {
      trailerParts.push(`${matchCount} match(es)`);
      if (models.size > 0) {
        trailerParts.push(`model(s): ${[...models].join(", ")}`);
      }
    }

    if (copilotSignals.length > 0) {
      trailerParts.push(formatCopilotTrailer(copilotSignals));
    }

    const value = trailerParts.join("; ");
    assert.equal(
      value,
      "2 match(es); model(s): gpt-4.1; copilot (copilot-agent); confidence: high",
    );
  });

  it("generates Copilot-only trailer when no code patterns found", () => {
    const matchCount = 0;
    const copilotSignals: CopilotSignal[] = [
      { source: "copilot-cli", confidence: "high", evidence: ["GH_COPILOT"] },
    ];

    const trailerParts: string[] = [];

    if (matchCount > 0) {
      trailerParts.push(`${matchCount} match(es)`);
    }

    if (copilotSignals.length > 0) {
      trailerParts.push(formatCopilotTrailer(copilotSignals));
    }

    const value = trailerParts.join("; ");
    assert.equal(value, "copilot (copilot-cli); confidence: high");
  });

  it("generates Claude Code trailer when no code patterns found", () => {
    const copilotSignals: CopilotSignal[] = [
      { source: "claude-code", confidence: "high", evidence: ["CLAUDE_CODE"] },
    ];
    const value = formatCopilotTrailer(copilotSignals);
    assert.equal(value, "claude (claude-code); confidence: high");
  });

  it("generates combined trailer with Cursor + pattern matches", () => {
    const matchCount = 3;
    const models = new Set(["claude-3.5-sonnet"]);
    const agentSignals: CopilotSignal[] = [
      { source: "cursor", confidence: "high", evidence: ["CURSOR_TRACE_ID"] },
    ];

    const trailerParts: string[] = [];
    if (matchCount > 0) {
      trailerParts.push(`${matchCount} match(es)`);
      if (models.size > 0) {
        trailerParts.push(`model(s): ${[...models].join(", ")}`);
      }
    }
    if (agentSignals.length > 0) {
      trailerParts.push(formatCopilotTrailer(agentSignals));
    }

    const value = trailerParts.join("; ");
    assert.equal(
      value,
      "3 match(es); model(s): claude-3.5-sonnet; cursor (cursor); confidence: high",
    );
  });
});
