import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import { writeFileSync, mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";
import { hashSnippet } from "../core/hasher.js";
import { matchFile } from "../core/matcher.js";
import type { Snippet, ScanMatch, ScanReport } from "../core/types.js";

// ── Integration: full pipeline from snippet creation → scan → report ─

function makeSnippet(content: string, opts?: Partial<Snippet>): Snippet {
  return {
    id: randomUUID(),
    hash: hashSnippet(content),
    source: "test",
    model: "gpt-4.1",
    addedAt: new Date().toISOString(),
    content,
    ...opts,
  };
}

function buildReport(
  files: Array<{ path: string; content: string }>,
  snippets: Snippet[],
): ScanReport {
  const allMatches: ScanMatch[] = [];
  const attributedFiles = new Set<string>();
  const suspiciousFiles = new Set<string>();
  const modelCounts = new Map<string, number>();

  for (const file of files) {
    const matches = matchFile(file.path, file.content, snippets, { fuzzy: true });
    for (const m of matches) {
      allMatches.push(m);
      if (m.snippet) {
        attributedFiles.add(m.file);
        if (m.snippet.model) {
          modelCounts.set(m.snippet.model, (modelCounts.get(m.snippet.model) ?? 0) + 1);
        }
      } else {
        suspiciousFiles.add(m.file);
      }
    }
  }

  for (const f of attributedFiles) suspiciousFiles.delete(f);

  let topModel: string | null = null;
  let topCount = 0;
  for (const [model, count] of modelCounts) {
    if (count > topCount) {
      topModel = model;
      topCount = count;
    }
  }

  return {
    filesAnalyzed: files.length,
    aiAttributedFiles: attributedFiles.size,
    unattributedSuspicious: suspiciousFiles.size,
    topModel,
    matches: allMatches,
  };
}

describe("integration — full scan pipeline", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = join(tmpdir(), `ai-footprint-integ-${randomUUID()}`);
    mkdirSync(tmpDir, { recursive: true });
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("produces correct report for mixed codebase", () => {
    const aiCode = `// generated by gpt-4
export function validateEmail(email: string): boolean {
  const emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;
  return emailRegex.test(email);
}`;

    const humanCode = `export function add(a: number, b: number): number {
  return a + b;
}`;

    const registeredCode = `export function multiply(a: number, b: number): number {
  return a * b;
}`;

    const snippet = makeSnippet(registeredCode);

    const files = [
      { path: "src/validators.ts", content: aiCode },
      { path: "src/math.ts", content: humanCode },
      { path: "src/multiply.ts", content: registeredCode },
    ];

    const report = buildReport(files, [snippet]);

    assert.equal(report.filesAnalyzed, 3);
    assert.ok(report.aiAttributedFiles >= 1); // multiply.ts (exact match), possibly more via fuzzy
    assert.ok(report.unattributedSuspicious >= 0); // validators.ts may be attributed via fuzzy
    assert.equal(report.topModel, "gpt-4.1");
    assert.ok(report.matches.length >= 2); // at least 1 exact + 1 pattern
  });

  it("attributes file wins over suspicious", () => {
    // File has both a registered snippet AND a pattern marker
    const code = `// generated by gpt-4
export function greet(name: string) {
  return "Hello " + name;
}`;

    const snippet = makeSnippet(code);
    const files = [{ path: "src/greet.ts", content: code }];
    const report = buildReport(files, [snippet]);

    // File should be counted as attributed, NOT suspicious
    assert.equal(report.aiAttributedFiles, 1);
    assert.equal(report.unattributedSuspicious, 0);
  });

  it("handles project with no AI code", () => {
    const files = [
      { path: "src/a.ts", content: "export const A = 1;" },
      { path: "src/b.ts", content: "export const B = 2;" },
    ];
    const report = buildReport(files, []);

    assert.equal(report.filesAnalyzed, 2);
    assert.equal(report.aiAttributedFiles, 0);
    assert.equal(report.unattributedSuspicious, 0);
    assert.equal(report.topModel, null);
    assert.equal(report.matches.length, 0);
  });

  it("handles project where all code is registered AI", () => {
    const code1 = "export function one() { return 1; }";
    const code2 = "export function two() { return 2; }";

    const files = [
      { path: "a.ts", content: code1 },
      { path: "b.ts", content: code2 },
    ];
    const snippets = [
      makeSnippet(code1, { model: "gpt-4.1" }),
      makeSnippet(code2, { model: "claude-3.5" }),
    ];

    const report = buildReport(files, snippets);

    assert.equal(report.aiAttributedFiles, 2);
    assert.equal(report.unattributedSuspicious, 0);
    assert.ok(report.topModel !== null);
  });

  it("detects fuzzy matches for modified AI code", () => {
    const original = `export function parseQuery(url: string): Record<string, string> {
  const params: Record<string, string> = {};
  const qs = url.split("?")[1];
  if (!qs) return params;
  for (const pair of qs.split("&")) {
    const [key, value] = pair.split("=");
    if (key) params[decodeURIComponent(key)] = decodeURIComponent(value || "");
  }
  return params;
}`;

    const modified = `export function extractParams(href: string): Map<string, string> {
  const result = new Map<string, string>();
  const qs = href.split("?")[1];
  if (!qs) return result;
  for (const seg of qs.split("&")) {
    const [k, v] = seg.split("=");
    if (k) result.set(decodeURIComponent(k), decodeURIComponent(v || ""));
  }
  return result;
}`;

    const snippet = makeSnippet(original);
    const files = [{ path: "utils.ts", content: modified }];
    const report = buildReport(files, [snippet]);

    const fuzzyMatches = report.matches.filter((m) => m.matchType === "fuzzy");
    // Fuzzy matching may or may not find a match depending on threshold/window.
    // The key test is that the pipeline doesn't crash and produces valid output.
    assert.ok(Array.isArray(report.matches));
    if (fuzzyMatches.length > 0) {
      assert.ok((fuzzyMatches[0].similarity ?? 0) > 0.4);
    }
  });

  it("handles multiple models and finds top model", () => {
    const code1 = "function a() { return 1; }";
    const code2 = "function b() { return 2; }";
    const code3 = "function c() { return 3; }";

    const snippets = [
      makeSnippet(code1, { model: "gpt-4.1" }),
      makeSnippet(code2, { model: "gpt-4.1" }),
      makeSnippet(code3, { model: "claude-3.5" }),
    ];

    const files = [
      { path: "a.ts", content: code1 },
      { path: "b.ts", content: code2 },
      { path: "c.ts", content: code3 },
    ];

    const report = buildReport(files, snippets);
    assert.equal(report.topModel, "gpt-4.1"); // 2 matches vs 1
  });
});

// ── E2E: CLI invocation ──────────────────────────────────────────────

describe("E2E — CLI help output", () => {
  it("shows help text with all commands", async () => {
    const { execSync } = await import("node:child_process");
    const output = execSync("node dist/cli/index.js --help", {
      encoding: "utf-8",
      cwd: process.cwd(),
    });

    assert.ok(output.includes("ai-footprint v0.1"));
    assert.ok(output.includes("init"));
    assert.ok(output.includes("add-snippet"));
    assert.ok(output.includes("track"));
    assert.ok(output.includes("scan"));
    assert.ok(output.includes("dashboard"));
  });
});
