import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { matchFile } from "../core/matcher.js";
import { hashSnippet } from "../core/hasher.js";
import type { Snippet } from "../core/types.js";

function makeSnippet(content: string, overrides?: Partial<Snippet>): Snippet {
  return {
    id: "test-id",
    hash: hashSnippet(content),
    source: "test",
    model: "test-model",
    addedAt: new Date().toISOString(),
    content,
    ...overrides,
  };
}

// ── Exact matching ───────────────────────────────────────────────────

describe("matchFile — exact matching", () => {
  it("finds an exact hash match for a registered snippet", () => {
    const code = "function hello() {\n  return 42;\n}";
    const snippet = makeSnippet(code);
    const matches = matchFile("test.ts", code, [snippet], { fuzzy: false });
    const exact = matches.filter((m) => m.matchType === "exact");
    assert.ok(exact.length > 0, "Should find at least one exact match");
    assert.equal(exact[0].confidence, "high");
    assert.equal(exact[0].similarity, 1.0);
    assert.equal(exact[0].snippet?.id, snippet.id);
  });

  it("returns no exact match for different code", () => {
    const snippet = makeSnippet("function hello() { return 42; }");
    const differentCode = "function goodbye() { return 0; }";
    const matches = matchFile("test.ts", differentCode, [snippet], { fuzzy: false });
    const exact = matches.filter((m) => m.matchType === "exact");
    assert.equal(exact.length, 0);
  });

  it("finds snippet embedded in a larger file", () => {
    const snippetCode = "function helper() {\n  return true;\n}";
    const snippet = makeSnippet(snippetCode);
    const fileContent = [
      "// header comment",
      "import { foo } from 'bar';",
      "",
      "function helper() {",
      "  return true;",
      "}",
      "",
      "export default helper;",
    ].join("\n");
    const matches = matchFile("test.ts", fileContent, [snippet], { fuzzy: false });
    const exact = matches.filter((m) => m.matchType === "exact");
    assert.ok(exact.length > 0, "Should find snippet inside larger file");
    assert.equal(exact[0].line, 4); // line of "function helper() {"
  });

  it("handles empty snippet list", () => {
    const matches = matchFile("test.ts", "some code", [], { fuzzy: false });
    assert.equal(matches.filter((m) => m.matchType === "exact").length, 0);
  });
});

// ── Pattern matching ─────────────────────────────────────────────────

describe("matchFile — pattern matching", () => {
  it("detects '// generated by gpt' comment", () => {
    const code = "// generated by gpt-4\nconst x = 1;";
    const matches = matchFile("test.ts", code, []);
    const patterns = matches.filter((m) => m.matchType === "pattern");
    assert.ok(patterns.length > 0);
    assert.equal(patterns[0].confidence, "medium");
  });

  it("detects '@ai-generated' tag", () => {
    const code = "/* @ai-generated */\nfunction foo() {}";
    const matches = matchFile("test.ts", code, []);
    const patterns = matches.filter((m) => m.matchType === "pattern");
    assert.ok(patterns.length > 0);
  });

  it("detects 'copilot' reference", () => {
    const code = "// Suggested by GitHub Copilot\nconst x = 1;";
    const matches = matchFile("test.ts", code, []);
    const patterns = matches.filter((m) => m.matchType === "pattern");
    assert.ok(patterns.length > 0);
    assert.ok(patterns.some((p) => p.pattern === "copilot-ref"));
  });

  it("detects AI-generated marker", () => {
    const code = "// AI-generated utility function\nfunction util() {}";
    const matches = matchFile("test.ts", code, []);
    const patterns = matches.filter((m) => m.matchType === "pattern");
    assert.ok(patterns.length > 0);
    assert.ok(patterns.some((p) => p.pattern === "marker"));
  });

  it("detects Python-style comment tag", () => {
    const code = "# generated by claude\ndef foo(): pass";
    const matches = matchFile("test.py", code, []);
    const patterns = matches.filter((m) => m.matchType === "pattern");
    assert.ok(patterns.length > 0);
  });

  it("returns no patterns for clean code", () => {
    const code = "function add(a: number, b: number) {\n  return a + b;\n}";
    const matches = matchFile("test.ts", code, []);
    const patterns = matches.filter((m) => m.matchType === "pattern");
    assert.equal(patterns.length, 0);
  });

  it("reports correct line numbers", () => {
    const code = "// line 1\n// line 2\n// generated by gpt\n// line 4";
    const matches = matchFile("test.ts", code, []);
    const patterns = matches.filter((m) => m.matchType === "pattern");
    assert.ok(patterns.some((p) => p.line === 3));
  });
});

// ── Combined matching ────────────────────────────────────────────────

describe("matchFile — combined exact + pattern", () => {
  it("returns both exact and pattern matches in one pass", () => {
    const snippetCode = "function helper() {\n  return true;\n}";
    const snippet = makeSnippet(snippetCode);
    const fileContent = [
      "// generated by gpt-4",
      "function helper() {",
      "  return true;",
      "}",
    ].join("\n");

    const matches = matchFile("test.ts", fileContent, [snippet], { fuzzy: false });
    const exact = matches.filter((m) => m.matchType === "exact");
    const pattern = matches.filter((m) => m.matchType === "pattern");
    assert.ok(exact.length > 0, "Should find exact match");
    assert.ok(pattern.length > 0, "Should find pattern match");
  });
});
