import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import { writeFileSync, mkdirSync, rmSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";

// We test the registry by pointing to a temp directory.
// Since the module uses homedir(), we isolate by calling the internal functions
// via the compiled JS that we import — but the registry path is hardcoded.
// Instead, we test via the CLI binary to simulate real usage.
// For unit tests, we test the addSnippet/loadRegistry/addDirectory logic
// by importing and indirectly testing through the scan function.

import { hashSnippet } from "../core/hasher.js";
import { matchFile } from "../core/matcher.js";
import type { Snippet, SnippetRegistry } from "../core/types.js";

// ── Registry-like unit tests (without touching real ~/.ai-footprint) ─

describe("registry logic — snippet creation", () => {
  it("creates a valid snippet object", () => {
    const content = "function test() { return 1; }";
    const snippet: Snippet = {
      id: randomUUID(),
      hash: hashSnippet(content),
      source: "chatgpt",
      model: "gpt-4.1",
      tool: "web",
      addedAt: new Date().toISOString(),
      content,
    };

    assert.ok(snippet.id.length > 0);
    assert.equal(snippet.hash.length, 64);
    assert.equal(snippet.source, "chatgpt");
    assert.equal(snippet.model, "gpt-4.1");
    assert.ok(snippet.content.includes("function test"));
  });

  it("registers and matches a snippet correctly", () => {
    const code = "export const PI = 3.14159;";
    const snippet: Snippet = {
      id: randomUUID(),
      hash: hashSnippet(code),
      source: "copilot",
      addedAt: new Date().toISOString(),
      content: code,
    };

    const matches = matchFile("constants.ts", code, [snippet], { fuzzy: false });
    const exact = matches.filter((m) => m.matchType === "exact");
    assert.ok(exact.length > 0);
    assert.equal(exact[0].snippet?.source, "copilot");
  });

  it("deduplicates by hash", () => {
    const code = "const x = 1;";
    const hash = hashSnippet(code);

    const registry: SnippetRegistry = { version: 1, snippets: [] };
    const existingHashes = new Set<string>();

    // First add
    existingHashes.add(hash);
    registry.snippets.push({
      id: randomUUID(),
      hash,
      source: "test",
      addedAt: new Date().toISOString(),
      content: code,
    });

    // Second add — should be skipped
    const shouldSkip = existingHashes.has(hash);
    assert.ok(shouldSkip, "Duplicate hash should be detected");
    assert.equal(registry.snippets.length, 1);
  });
});

// ── Scanner-like tests (file walking + matching) ─────────────────────

describe("scanner logic", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = join(tmpdir(), `ai-footprint-test-${randomUUID()}`);
    mkdirSync(tmpDir, { recursive: true });
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("matches files in a directory with pattern detection", () => {
    const srcDir = join(tmpDir, "src");
    mkdirSync(srcDir);
    writeFileSync(
      join(srcDir, "util.ts"),
      "// generated by gpt-4\nexport function foo() { return 1; }\n",
    );
    writeFileSync(
      join(srcDir, "clean.ts"),
      "export function bar() { return 2; }\n",
    );

    // Read and match each file manually (simulating scanner)
    const utilContent = readFileSync(join(srcDir, "util.ts"), "utf-8");
    const cleanContent = readFileSync(join(srcDir, "clean.ts"), "utf-8");

    const utilMatches = matchFile("src/util.ts", utilContent, []);
    const cleanMatches = matchFile("src/clean.ts", cleanContent, []);

    assert.ok(utilMatches.length > 0, "util.ts should have pattern matches");
    assert.equal(cleanMatches.length, 0, "clean.ts should have no matches");
  });

  it("matches registered snippets across multiple files", () => {
    const codeA = "function helperA() {\n  return true;\n}";
    const codeB = "function helperB() {\n  return false;\n}";

    const snippetA: Snippet = {
      id: randomUUID(),
      hash: hashSnippet(codeA),
      source: "copilot",
      model: "gpt-4.1",
      addedAt: new Date().toISOString(),
      content: codeA,
    };

    writeFileSync(join(tmpDir, "a.ts"), codeA);
    writeFileSync(join(tmpDir, "b.ts"), codeB);

    const matchesA = matchFile("a.ts", codeA, [snippetA], { fuzzy: false });
    const matchesB = matchFile("b.ts", codeB, [snippetA], { fuzzy: false });

    const exactA = matchesA.filter((m) => m.matchType === "exact");
    const exactB = matchesB.filter((m) => m.matchType === "exact");

    assert.ok(exactA.length > 0, "a.ts should match registered snippet");
    assert.equal(exactB.length, 0, "b.ts should not match");
  });

  it("generates a correct scan report shape", () => {
    const code = "// AI-generated code\nfunction foo() {}";
    const content = readFileSync(
      (writeFileSync(join(tmpDir, "test.ts"), code), join(tmpDir, "test.ts")),
      "utf-8",
    );

    const matches = matchFile("test.ts", content, []);
    const attributedFiles = new Set<string>();
    const suspiciousFiles = new Set<string>();

    for (const m of matches) {
      if (m.snippet) {
        attributedFiles.add(m.file);
      } else {
        suspiciousFiles.add(m.file);
      }
    }

    for (const f of attributedFiles) suspiciousFiles.delete(f);

    assert.ok(suspiciousFiles.has("test.ts"));
    assert.equal(attributedFiles.size, 0);
  });
});
