/**
 * Copilot agent detection module.
 *
 * Detects whether a commit was authored (wholly or partly) by
 * GitHub Copilot — either the VS Code agent/chat, or the CLI (`gh copilot`).
 *
 * Detection signals (in order of reliability):
 *  1. Marker file written by the AI Footprint VS Code extension when it
 *     observes Copilot-originated edits.
 *  2. Environment variables set by `gh copilot` or VS Code Copilot agent.
 *  3. Commit message patterns commonly produced by Copilot agent.
 */

import {
  existsSync,
  readFileSync,
  writeFileSync,
  unlinkSync,
  mkdirSync,
} from "node:fs";
import { join, dirname } from "node:path";

// ------------------------------------------------------------------ //
// Types
// ------------------------------------------------------------------ //

export interface CopilotSignal {
  source: "copilot-agent" | "copilot-cli" | "copilot-chat";
  confidence: "high" | "medium" | "low";
  evidence: string[];
  /** Files identified as Copilot-edited (from marker file). */
  files?: string[];
}

export interface CopilotMarker {
  files: string[];
  updatedAt: string;
}

// ------------------------------------------------------------------ //
// Commit message patterns
// ------------------------------------------------------------------ //

const COPILOT_MSG_PATTERNS: { pattern: RegExp; label: string }[] = [
  { pattern: /co-authored-by:\s*.*copilot/i, label: "Co-authored-by Copilot trailer" },
  { pattern: /co-authored-by:\s*.*\[bot\]/i, label: "Co-authored-by [bot] trailer" },
  { pattern: /\bgithub[\s._-]*copilot\b/i, label: "GitHub Copilot mention" },
  { pattern: /\bcopilot[\s._-]*agent\b/i, label: "Copilot agent mention" },
  { pattern: /^generated\s+by\s+copilot/im, label: "Generated by Copilot prefix" },
];

/** Marker file name (relative to repo root). */
const MARKER_DIR = ".ai-footprint";
const MARKER_FILE = "copilot-pending.json";

// ------------------------------------------------------------------ //
// Public API
// ------------------------------------------------------------------ //

/**
 * Detect Copilot agent signals from multiple sources.
 * Returns an array of signals (may be empty).
 */
export function detectCopilotSignals(opts?: {
  commitMessage?: string;
  repoRoot?: string;
}): CopilotSignal[] {
  const signals: CopilotSignal[] = [];

  // 1. Marker file (highest reliability — written by our extension)
  const markerSignal = detectCopilotMarker(opts?.repoRoot);
  if (markerSignal) signals.push(markerSignal);

  // 2. Copilot CLI environment variables
  const cliSignal = detectCopilotCLI();
  if (cliSignal) signals.push(cliSignal);

  // 3. Commit message patterns
  if (opts?.commitMessage) {
    const msgSignal = detectCopilotCommitMessage(opts.commitMessage);
    if (msgSignal) signals.push(msgSignal);
  }

  return signals;
}

/**
 * Format Copilot signals into a trailer value string.
 */
export function formatCopilotTrailer(signals: CopilotSignal[]): string {
  if (signals.length === 0) return "";

  const sources = [...new Set(signals.map((s) => s.source))];
  const highestConfidence = signals.some((s) => s.confidence === "high")
    ? "high"
    : signals.some((s) => s.confidence === "medium")
      ? "medium"
      : "low";

  return `copilot (${sources.join(", ")}); confidence: ${highestConfidence}`;
}

// ------------------------------------------------------------------ //
// Marker file management (for the VS Code extension)
// ------------------------------------------------------------------ //

/**
 * Write or append to the Copilot marker file.
 * Called by the VS Code extension when Copilot edits are detected.
 */
export function writeCopilotMarker(files: string[], repoRoot: string): void {
  const dir = join(repoRoot, MARKER_DIR);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const markerPath = join(dir, MARKER_FILE);

  // Merge with existing entries
  let existing: string[] = [];
  if (existsSync(markerPath)) {
    try {
      const data = JSON.parse(readFileSync(markerPath, "utf-8")) as CopilotMarker;
      if (Array.isArray(data.files)) existing = data.files;
    } catch {
      /* corrupted — overwrite */
    }
  }

  const merged = [...new Set([...existing, ...files])];
  const marker: CopilotMarker = {
    files: merged,
    updatedAt: new Date().toISOString(),
  };
  writeFileSync(markerPath, JSON.stringify(marker, null, 2));
}

/**
 * Clear the Copilot marker file after a commit.
 */
export function clearCopilotMarker(repoRoot: string): void {
  const markerPath = join(repoRoot, MARKER_DIR, MARKER_FILE);
  if (existsSync(markerPath)) {
    try {
      unlinkSync(markerPath);
    } catch {
      /* best-effort */
    }
  }
}

// ------------------------------------------------------------------ //
// Git root discovery (no shelling out)
// ------------------------------------------------------------------ //

/**
 * Walk upward from `startDir` to find the repo root (directory containing `.git`).
 */
export function findGitRoot(startDir?: string): string | null {
  let dir = startDir ?? process.cwd();
  for (;;) {
    if (existsSync(join(dir, ".git"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) return null; // filesystem root reached
    dir = parent;
  }
}

// ------------------------------------------------------------------ //
// Internal detectors
// ------------------------------------------------------------------ //

function detectCopilotMarker(repoRoot?: string): CopilotSignal | null {
  const root = repoRoot ?? findGitRoot();
  if (!root) return null;

  const markerPath = join(root, MARKER_DIR, MARKER_FILE);
  if (!existsSync(markerPath)) return null;

  try {
    const data = JSON.parse(readFileSync(markerPath, "utf-8")) as CopilotMarker;
    if (!Array.isArray(data.files) || data.files.length === 0) return null;

    return {
      source: "copilot-agent",
      confidence: "high",
      evidence: [`marker file lists ${data.files.length} Copilot-edited file(s)`],
      files: data.files,
    };
  } catch {
    return null;
  }
}

function detectCopilotCLI(): CopilotSignal | null {
  const evidence: string[] = [];

  if (process.env.GH_COPILOT) {
    evidence.push("GH_COPILOT env var present");
  }
  if (process.env.GITHUB_COPILOT_CLI) {
    evidence.push("GITHUB_COPILOT_CLI env var present");
  }
  // gh copilot suggest sets GH_PROMPT in some versions
  if (process.env.GH_PROMPT?.toLowerCase().includes("copilot")) {
    evidence.push("GH_PROMPT contains copilot");
  }

  if (evidence.length === 0) return null;
  return { source: "copilot-cli", confidence: "high", evidence };
}

function detectCopilotCommitMessage(message: string): CopilotSignal | null {
  const evidence: string[] = [];

  for (const { pattern, label } of COPILOT_MSG_PATTERNS) {
    if (pattern.test(message)) {
      evidence.push(label);
    }
  }

  if (evidence.length === 0) return null;
  return { source: "copilot-chat", confidence: "medium", evidence };
}
