/**
 * AI agent detection module.
 *
 * Detects whether a commit was authored (wholly or partly) by an AI coding
 * agent. Supports multiple agents:
 *
 *  - **GitHub Copilot** (VS Code agent/chat, CLI `gh copilot`)
 *  - **Claude Code** (Anthropic CLI agent)
 *  - **Cursor** (AI-powered editor)
 *  - **Lovable** (AI app builder, formerly GPT Engineer)
 *
 * Detection signals (in order of reliability):
 *  1. Marker file written by the AI Footprint VS Code extension when it
 *     observes AI-agent-originated edits.
 *  2. Environment variables set by agent CLIs or editors.
 *  3. Commit message / author patterns commonly produced by each agent.
 */

import {
  existsSync,
  readFileSync,
  writeFileSync,
  unlinkSync,
  mkdirSync,
} from "node:fs";
import { join, dirname } from "node:path";

// ------------------------------------------------------------------ //
// Types
// ------------------------------------------------------------------ //

/** Identifies which AI agent produced the code. */
export type AgentSource =
  | "copilot-agent"
  | "copilot-cli"
  | "copilot-chat"
  | "claude-code"
  | "cursor"
  | "lovable";

/** A single detected AI-agent signal. */
export interface AgentSignal {
  source: AgentSource;
  confidence: "high" | "medium" | "low";
  evidence: string[];
  /** Files identified as agent-edited (from marker file). */
  files?: string[];
}

// Keep backward-compat aliases
export type CopilotSignal = AgentSignal;

export interface AgentMarker {
  files: string[];
  /** Which agent wrote these files (optional — if absent, inferred). */
  agent?: string;
  updatedAt: string;
}

// Keep backward-compat alias
export type CopilotMarker = AgentMarker;

// ------------------------------------------------------------------ //
// Agent-specific detection definitions
// ------------------------------------------------------------------ //

interface EnvRule {
  envVar: string;
  /** If set, the env var value must contain this substring (case-insensitive). */
  valueContains?: string;
  label: string;
}

interface MsgRule {
  pattern: RegExp;
  label: string;
}

interface AgentDef {
  source: AgentSource;
  envConfidence: "high" | "medium" | "low";
  msgConfidence: "high" | "medium" | "low";
  envRules: EnvRule[];
  msgRules: MsgRule[];
  /** Check git author name/email for this pattern. */
  authorPatterns?: RegExp[];
}

const AGENTS: AgentDef[] = [
  // --- GitHub Copilot CLI ------------------------------------------------
  {
    source: "copilot-cli",
    envConfidence: "high",
    msgConfidence: "medium",
    envRules: [
      { envVar: "GH_COPILOT", label: "GH_COPILOT env var present" },
      { envVar: "GITHUB_COPILOT_CLI", label: "GITHUB_COPILOT_CLI env var present" },
      { envVar: "GH_PROMPT", valueContains: "copilot", label: "GH_PROMPT contains copilot" },
    ],
    msgRules: [],
  },

  // --- GitHub Copilot Chat / Agent ---------------------------------------
  {
    source: "copilot-chat",
    envConfidence: "medium",
    msgConfidence: "medium",
    envRules: [],
    msgRules: [
      { pattern: /co-authored-by:\s*.*copilot/i, label: "Co-authored-by Copilot trailer" },
      { pattern: /\bgithub[\s._-]*copilot\b/i, label: "GitHub Copilot mention" },
      { pattern: /\bcopilot[\s._-]*agent\b/i, label: "Copilot agent mention" },
      { pattern: /^generated\s+by\s+copilot/im, label: "Generated by Copilot prefix" },
    ],
  },

  // --- Claude Code -------------------------------------------------------
  {
    source: "claude-code",
    envConfidence: "high",
    msgConfidence: "medium",
    envRules: [
      { envVar: "CLAUDE_CODE", label: "CLAUDE_CODE env var present" },
      { envVar: "CLAUDE_CODE_ENTRY", label: "CLAUDE_CODE_ENTRY env var present" },
      { envVar: "ANTHROPIC_API_KEY", label: "ANTHROPIC_API_KEY env var present (Claude tooling)" },
    ],
    msgRules: [
      { pattern: /co-authored-by:\s*.*claude/i, label: "Co-authored-by Claude trailer" },
      { pattern: /\bclaude[\s._-]*code\b/i, label: "Claude Code mention" },
      { pattern: /^generated\s+by\s+claude/im, label: "Generated by Claude prefix" },
      { pattern: /\banthropic[\s._-]*claude\b/i, label: "Anthropic Claude mention" },
    ],
  },

  // --- Cursor ------------------------------------------------------------
  {
    source: "cursor",
    envConfidence: "high",
    msgConfidence: "medium",
    envRules: [
      { envVar: "CURSOR_TRACE_ID", label: "CURSOR_TRACE_ID env var present" },
      { envVar: "TERM_PROGRAM", valueContains: "cursor", label: "TERM_PROGRAM is cursor" },
      { envVar: "CURSOR_CHANNEL", label: "CURSOR_CHANNEL env var present" },
    ],
    msgRules: [
      { pattern: /\bcursor[\s._-]*(?:composer|agent|ai)\b/i, label: "Cursor agent mention" },
      { pattern: /co-authored-by:\s*.*cursor/i, label: "Co-authored-by Cursor trailer" },
      { pattern: /^generated\s+by\s+cursor/im, label: "Generated by Cursor prefix" },
    ],
  },

  // --- Lovable (formerly GPT Engineer) -----------------------------------
  {
    source: "lovable",
    envConfidence: "high",
    msgConfidence: "medium",
    envRules: [
      { envVar: "LOVABLE_TOKEN", label: "LOVABLE_TOKEN env var present" },
      { envVar: "GPTENGINEER_TOKEN", label: "GPTENGINEER_TOKEN env var present" },
    ],
    msgRules: [
      { pattern: /\blovable[\s._-]*(?:dev|bot|ai)\b/i, label: "Lovable mention" },
      { pattern: /co-authored-by:\s*.*lovable/i, label: "Co-authored-by Lovable trailer" },
      { pattern: /\bgpt[\s._-]*engineer\b/i, label: "GPT Engineer mention" },
    ],
    authorPatterns: [
      /lovable-dev\[bot\]/i,
      /lovable\[bot\]/i,
      /gptengineer\[bot\]/i,
    ],
  },
];

// Bot author patterns that indicate any AI agent
const GENERIC_BOT_PATTERN = /co-authored-by:\s*.*\[bot\]/i;

/** Marker file name (relative to repo root). */
const MARKER_DIR = ".ai-footprint";
const MARKER_FILE = "copilot-pending.json";

// ------------------------------------------------------------------ //
// Public API
// ------------------------------------------------------------------ //

/**
 * Detect AI-agent signals from multiple sources.
 * Returns an array of signals (may be empty).
 */
export function detectCopilotSignals(opts?: {
  commitMessage?: string;
  commitAuthor?: string;
  repoRoot?: string;
}): AgentSignal[] {
  const signals: AgentSignal[] = [];

  // 1. Marker file (highest reliability — written by our extension)
  const markerSignal = detectAgentMarker(opts?.repoRoot);
  if (markerSignal) signals.push(markerSignal);

  // 2. Per-agent environment variable checks
  for (const agent of AGENTS) {
    const envSignal = detectAgentEnv(agent);
    if (envSignal) signals.push(envSignal);
  }

  // 3. Commit message + author patterns
  if (opts?.commitMessage) {
    for (const agent of AGENTS) {
      const msgSignal = detectAgentMessage(agent, opts.commitMessage, opts.commitAuthor);
      if (msgSignal) signals.push(msgSignal);
    }

    // Generic [bot] author (if no specific agent matched it already)
    if (
      GENERIC_BOT_PATTERN.test(opts.commitMessage) &&
      !signals.some((s) => s.evidence.some((e) => e.includes("[bot]") || e.includes("Co-authored-by")))
    ) {
      signals.push({
        source: "copilot-chat",
        confidence: "low",
        evidence: ["Co-authored-by [bot] trailer (unknown agent)"],
      });
    }
  }

  return signals;
}

// Keep the old name as the canonical export — all callers already use it.
export { detectCopilotSignals as detectAgentSignals };

/**
 * Format agent signals into a trailer value string.
 */
export function formatCopilotTrailer(signals: AgentSignal[]): string {
  if (signals.length === 0) return "";

  const sources = [...new Set(signals.map((s) => s.source))];
  const highestConfidence = signals.some((s) => s.confidence === "high")
    ? "high"
    : signals.some((s) => s.confidence === "medium")
      ? "medium"
      : "low";

  // Group by tool family for cleaner output
  const families = [...new Set(sources.map(sourceFamily))];
  const label = families.length === 1
    ? `${families[0]} (${sources.join(", ")})`
    : sources.join(", ");

  return `${label}; confidence: ${highestConfidence}`;
}

export { formatCopilotTrailer as formatAgentTrailer };

/** Map a source to its human-readable family name. */
function sourceFamily(source: AgentSource): string {
  if (source.startsWith("copilot")) return "copilot";
  if (source === "claude-code") return "claude";
  if (source === "cursor") return "cursor";
  if (source === "lovable") return "lovable";
  return source;
}

// ------------------------------------------------------------------ //
// Marker file management (for the VS Code extension)
// ------------------------------------------------------------------ //

/**
 * Write or append to the agent marker file.
 * Called by the VS Code extension when AI-agent edits are detected.
 */
export function writeCopilotMarker(files: string[], repoRoot: string, agent?: string): void {
  const dir = join(repoRoot, MARKER_DIR);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const markerPath = join(dir, MARKER_FILE);

  // Merge with existing entries
  let existing: string[] = [];
  let existingAgent: string | undefined;
  if (existsSync(markerPath)) {
    try {
      const data = JSON.parse(readFileSync(markerPath, "utf-8")) as AgentMarker;
      if (Array.isArray(data.files)) existing = data.files;
      existingAgent = data.agent;
    } catch {
      /* corrupted — overwrite */
    }
  }

  const merged = [...new Set([...existing, ...files])];
  const marker: AgentMarker = {
    files: merged,
    agent: agent ?? existingAgent,
    updatedAt: new Date().toISOString(),
  };
  writeFileSync(markerPath, JSON.stringify(marker, null, 2));
}

export { writeCopilotMarker as writeAgentMarker };

/**
 * Clear the agent marker file after a commit.
 */
export function clearCopilotMarker(repoRoot: string): void {
  const markerPath = join(repoRoot, MARKER_DIR, MARKER_FILE);
  if (existsSync(markerPath)) {
    try {
      unlinkSync(markerPath);
    } catch {
      /* best-effort */
    }
  }
}

export { clearCopilotMarker as clearAgentMarker };

// ------------------------------------------------------------------ //
// Git root discovery (no shelling out)
// ------------------------------------------------------------------ //

/**
 * Walk upward from `startDir` to find the repo root (directory containing `.git`).
 */
export function findGitRoot(startDir?: string): string | null {
  let dir = startDir ?? process.cwd();
  for (;;) {
    if (existsSync(join(dir, ".git"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) return null; // filesystem root reached
    dir = parent;
  }
}

// ------------------------------------------------------------------ //
// Internal detectors
// ------------------------------------------------------------------ //

function detectAgentMarker(repoRoot?: string): AgentSignal | null {
  const root = repoRoot ?? findGitRoot();
  if (!root) return null;

  const markerPath = join(root, MARKER_DIR, MARKER_FILE);
  if (!existsSync(markerPath)) return null;

  try {
    const data = JSON.parse(readFileSync(markerPath, "utf-8")) as AgentMarker;
    if (!Array.isArray(data.files) || data.files.length === 0) return null;

    const agentSource: AgentSource = (data.agent as AgentSource) ?? "copilot-agent";

    return {
      source: agentSource,
      confidence: "high",
      evidence: [`marker file lists ${data.files.length} AI-edited file(s)` +
        (data.agent ? ` (agent: ${data.agent})` : "")],
      files: data.files,
    };
  } catch {
    return null;
  }
}

function detectAgentEnv(agent: AgentDef): AgentSignal | null {
  const evidence: string[] = [];

  for (const rule of agent.envRules) {
    const val = process.env[rule.envVar];
    if (!val) continue;

    if (rule.valueContains) {
      if (val.toLowerCase().includes(rule.valueContains)) {
        evidence.push(rule.label);
      }
    } else {
      evidence.push(rule.label);
    }
  }

  if (evidence.length === 0) return null;
  return { source: agent.source, confidence: agent.envConfidence, evidence };
}

function detectAgentMessage(
  agent: AgentDef,
  message: string,
  author?: string,
): AgentSignal | null {
  const evidence: string[] = [];

  for (const rule of agent.msgRules) {
    if (rule.pattern.test(message)) {
      evidence.push(rule.label);
    }
  }

  // Check author patterns (e.g., lovable-dev[bot])
  if (author && agent.authorPatterns) {
    for (const ap of agent.authorPatterns) {
      if (ap.test(author)) {
        evidence.push(`git author matches ${ap.source}`);
      }
    }
  }

  if (evidence.length === 0) return null;
  return { source: agent.source, confidence: agent.msgConfidence, evidence };
}
