// examples/enterprise-api/src/auth.ts
// Simulates an enterprise API module with mixed human + AI code.

// -- Human-written authentication core --

import { createHash, randomBytes } from "node:crypto";

export interface AuthConfig {
  secret: string;
  tokenTtlSeconds: number;
  issuer: string;
}

export function hashPassword(password: string, salt: string): string {
  return createHash("sha256").update(salt + password).digest("hex");
}

export function generateSalt(): string {
  return randomBytes(16).toString("hex");
}

// -- AI-generated helper (from ChatGPT, model: gpt-4.1) --
// generated by gpt-4.1

export function validateEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

export function validatePassword(password: string): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];
  if (password.length < 8) errors.push("Password must be at least 8 characters");
  if (!/[A-Z]/.test(password)) errors.push("Password must contain an uppercase letter");
  if (!/[a-z]/.test(password)) errors.push("Password must contain a lowercase letter");
  if (!/[0-9]/.test(password)) errors.push("Password must contain a number");
  if (!/[^A-Za-z0-9]/.test(password)) errors.push("Password must contain a special character");
  return { valid: errors.length === 0, errors };
}

// -- AI-generated RBAC helper (from Copilot) --
// @ai-generated by GitHub Copilot

export type Role = "admin" | "editor" | "viewer";

const ROLE_HIERARCHY: Record<Role, number> = {
  admin: 3,
  editor: 2,
  viewer: 1,
};

export function hasPermission(userRole: Role, requiredRole: Role): boolean {
  return ROLE_HIERARCHY[userRole] >= ROLE_HIERARCHY[requiredRole];
}

export function filterByPermission<T extends { requiredRole: Role }>(
  items: T[],
  userRole: Role,
): T[] {
  return items.filter((item) => hasPermission(userRole, item.requiredRole));
}
