// examples/enterprise-api/src/data-pipeline.ts
// Simulates a data processing module with AI-generated transformations.

export interface DataRecord {
  id: string;
  timestamp: string;
  payload: Record<string, unknown>;
  source: string;
}

export interface PipelineConfig {
  batchSize: number;
  retryLimit: number;
  deduplicateBy: string;
}

// -- Human-written pipeline orchestrator --

export class DataPipeline {
  private config: PipelineConfig;
  private processors: Array<(records: DataRecord[]) => DataRecord[]> = [];

  constructor(config: PipelineConfig) {
    this.config = config;
  }

  addProcessor(fn: (records: DataRecord[]) => DataRecord[]): this {
    this.processors.push(fn);
    return this;
  }

  process(records: DataRecord[]): DataRecord[] {
    let result = records;
    for (const processor of this.processors) {
      result = processor(result);
    }
    return result;
  }
}

// -- AI-generated utility functions (Claude 3.5 Sonnet) --
// generated by claude

export function deduplicateRecords(
  records: DataRecord[],
  key: string,
): DataRecord[] {
  const seen = new Map<unknown, DataRecord>();
  for (const record of records) {
    const value = record.payload[key];
    if (!seen.has(value)) {
      seen.set(value, record);
    }
  }
  return Array.from(seen.values());
}

export function batchRecords(
  records: DataRecord[],
  batchSize: number,
): DataRecord[][] {
  const batches: DataRecord[][] = [];
  for (let i = 0; i < records.length; i += batchSize) {
    batches.push(records.slice(i, i + batchSize));
  }
  return batches;
}

export function sortByTimestamp(records: DataRecord[]): DataRecord[] {
  return [...records].sort(
    (a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime(),
  );
}

export function filterByDateRange(
  records: DataRecord[],
  start: Date,
  end: Date,
): DataRecord[] {
  return records.filter((r) => {
    const ts = new Date(r.timestamp).getTime();
    return ts >= start.getTime() && ts <= end.getTime();
  });
}

// -- AI-generated aggregation (Gemini 1.5 Pro) --
// generated by gemini

export function aggregateBySource(
  records: DataRecord[],
): Map<string, { count: number; latest: string }> {
  const result = new Map<string, { count: number; latest: string }>();
  for (const record of records) {
    const existing = result.get(record.source);
    if (!existing) {
      result.set(record.source, { count: 1, latest: record.timestamp });
    } else {
      existing.count++;
      if (record.timestamp > existing.latest) {
        existing.latest = record.timestamp;
      }
    }
  }
  return result;
}
