// examples/fuzzy-matching-demo/original-snippet.ts
// Original AI-generated code registered as a snippet.
// This is the "source of truth" that gets registered in the snippet registry.

// AI-generated by gpt-4.1 via ChatGPT

export function parseQueryString(url: string): Record<string, string> {
  const params: Record<string, string> = {};
  const queryString = url.split("?")[1];
  if (!queryString) return params;

  for (const pair of queryString.split("&")) {
    const [key, value] = pair.split("=");
    if (key) {
      params[decodeURIComponent(key)] = decodeURIComponent(value || "");
    }
  }
  return params;
}

export function buildQueryString(params: Record<string, string>): string {
  const pairs: string[] = [];
  for (const [key, value] of Object.entries(params)) {
    pairs.push(`${encodeURIComponent(key)}=${encodeURIComponent(value)}`);
  }
  return pairs.length > 0 ? `?${pairs.join("&")}` : "";
}
