#!/usr/bin/env node
// Post a PR comment with the AI Footprint scan report.

import { readFileSync } from "node:fs";

const token = process.env.GITHUB_TOKEN;
const eventPath = process.env.GITHUB_EVENT_PATH;
const repository = process.env.GITHUB_REPOSITORY;

if (!token || !eventPath || !repository) {
  console.log("Skipping PR comment — missing GitHub context.");
  process.exit(0);
}

const report = JSON.parse(process.env.AI_FOOTPRINT_REPORT || "{}");
const event = JSON.parse(readFileSync(eventPath, "utf-8"));
const prNumber = event?.pull_request?.number;

if (!prNumber) {
  console.log("Skipping PR comment — not a pull request event.");
  process.exit(0);
}

const matches = report.matches || [];
const matchRows = matches
  .slice(0, 50)  // Cap at 50 to keep the comment readable
  .map(
    (m) =>
      `| \`${m.file}\` | ${m.line} | ${m.matchType ?? "—"} | ${m.confidence} | ${m.snippet ? (m.snippet.model ?? m.snippet.source) : m.pattern} | ${m.similarity != null ? Math.round(m.similarity * 100) + "%" : "—"} |`,
  )
  .join("\n");

const body = `## 🤖 AI Footprint Scan

| Metric | Value |
|--------|-------|
| Files analyzed | ${report.filesAnalyzed ?? 0} |
| AI-attributed files | ${report.aiAttributedFiles ?? 0} |
| Top model | ${report.topModel ?? "none"} |
| Unattributed suspicious | ${report.unattributedSuspicious ?? 0} |
| Total matches | ${matches.length} |

${
  matches.length > 0
    ? `### Matches

| File | Line | Type | Confidence | Source | Similarity |
|------|------|------|------------|--------|------------|
${matchRows}
${matches.length > 50 ? `\n*...and ${matches.length - 50} more.*` : ""}`
    : "✅ No AI-generated code detected."
}

---
<sub>Generated by [AI Footprint](https://github.com/${repository})</sub>`;

const [owner, repo] = repository.split("/");
const url = `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`;

const response = await fetch(url, {
  method: "POST",
  headers: {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({ body }),
});

if (response.ok) {
  console.log(`Posted AI Footprint report to PR #${prNumber}.`);
} else {
  const text = await response.text();
  console.error(`Failed to post PR comment: ${response.status} — ${text}`);
  process.exit(1);
}
